package com.example.primarydetailkotlin.di

import com.example.primarydetailkotlin.posts.services.ApiService
import com.example.primarydetailkotlin.util.BASE_URL
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import kotlinx.serialization.json.Json
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.kotlinx.serialization.asConverterFactory
import javax.inject.Singleton

/**
 * Hilt module for providing network-related dependencies.
 *
 * This module is installed in the [SingletonComponent], meaning dependencies provided here
 * are singletons and live for the entire lifecycle of the application.
 */
@Module
@InstallIn(SingletonComponent::class)
object NetworkModule {

    /**
     * Provides a configured [OkHttpClient].
     *
     * This client includes a [HttpLoggingInterceptor] to log the body of HTTP requests and responses,
     * which is useful for debugging.
     *
     * @return A configured [OkHttpClient] instance.
     */
    @Provides
    fun provideOkHttpClient(): OkHttpClient {
        val logging = HttpLoggingInterceptor()
        logging.level = HttpLoggingInterceptor.Level.BODY
        return OkHttpClient().newBuilder()
            .addInterceptor(logging)
            .build()
    }

    /**
     * Provides a configured [Retrofit] instance.
     *
     * This instance is configured with the base URL, the provided [OkHttpClient],
     * and a Kotlin Serialization converter for parsing JSON responses.
     *
     * @param okHttpClient The [OkHttpClient] to use for requests.
     * @return A configured [Retrofit] instance.
     */
    @Singleton
    @Provides
    fun provideRetrofit(okHttpClient: OkHttpClient): Retrofit {
        return Retrofit.Builder()
            .baseUrl(BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(Json.asConverterFactory("application/json".toMediaType()))
            .build()
    }

    /**
     * Provides an instance of the [ApiService] interface.
     *
     * This implementation is generated by Retrofit.
     *
     * @param retrofit The [Retrofit] instance used to create the service.
     * @return An implementation of [ApiService].
     */
    @Provides
    fun provideApiService(retrofit: Retrofit): ApiService = retrofit.create(ApiService::class.java)
}
